classDiagram
    class Пользователь {
        +Int id
        +Object фото
        +String имя
        +String email
        +String телефон
        +String роль
        +Boolean статус
        +авторизоваться()
        +сменитьФото()
        +оставитьОтзыв()
    }

    class Платежная_карта {
        +Int id
        +Date срок_действия
        +String номер
        +Object владелец
        +Boolean статус
        +удалить()
        +выбратьКарту()
        +обновитьДетали()
    }

    class Файл {
        +Int id
        +String имя
        +Object владелец
        +String путь
        +String тип
        +удалить()
        +скачать()
        +загрузить()
    }

    class Оплата {
        +Int id
        +Float сумма
        +Object бронирование
        +Date дата
        +String метод
        +String статус
        +отменить()
        +подтвердить()
        +создатьПлатеж()
    }

    class Жалоба {
        +Int id
        +Date дата
        +String статус
        +Object инициатор
        +Object цель
        +String текст
        +отклонить()
        +податьЖалобу()
        +рассмотреть()
    }

    class Сообщение {
        +Int id
        +Object чат
        +Object получатель
        +Object отправитель
        +Date время
        +String текст
        +удалить()
        +отправить()
        +просмотретьИсторию()
    }

    class Карточка_объекта {
        +Int id
        +String адрес
        +String описание
        +List фотографии
        +Float цена
        +добавитьЖилье()
        +искатьЖилье()
        +обновитьДетали()
    }

    class Обзор {
        +Int id
        +Object автор
        +Date дата
        +Float рейтинг
        +Object цель
        +String текст
        +добавитьОтзыв()
        +модерировать()
    }

    class Бронирование {
        +Int id
        +Float сумма
        +Object жилье
        +Date дата_заселения
        +Date дата_выселения
        +Object арендатор
        +Object арендодатель
        +String статус
        +отменить()
        +подтвердить()
        +создатьБронирование()
        +заблокироватьДепозит()
    }

    Пользователь "1" -- "*" Платежная_карта : владеет
    Пользователь "1" -- "*" Файл : загружает
    Пользователь "1" -- "*" Бронирование : арендатор/арендодатель
    Пользователь "1" -- "*" Жалоба : инициатор
    Пользователь "1" -- "*" Обзор : автор
    Карточка_объекта "1" -- "*" Файл : содержит_фото
    Бронирование "1" -- "*" Оплата : сопровождается
    Карточка_объекта "1" -- "*" Бронирование : объект_сдачи
